"""Generated unit tests for bug-fix pipeline run 001.

Generated by: Unit Test Generator agent (agents/unit-test-generator.agent.md)
Model: composer-2.5
FIRST skill applied: skills/unit-tests-FIRST.md

Scope (per fix-summary.md — changed functions only):
  - add_expense   → SEC-001 fix: eval() replaced with float()
  - get_total     → BUG-001 fix: EXPENSES[1:] replaced with EXPENSES
  - get_expenses  → BUG-002 fix: case-sensitive == replaced with .lower() == .lower()

FIRST compliance:
  Fast        — no I/O, no network, no sleep; all tests < 5 ms each
  Independent — relies on autouse reset_expenses fixture from conftest.py
  Repeatable  — no randomness, no time-dependency, deterministic expected values
  Self-validating — every test has ≥1 explicit assert with clear failure message
  Timely      — tests cover only the three functions changed in this pipeline run

Note: tests/test_expense_tracker.py already covers the basic happy-paths.
      These generated tests add targeted REGRESSION tests for each specific fix.
"""
import pytest
from src.expense_tracker import add_expense, get_expenses, get_total


# ──────────────────────────────────────────────────────────────────────────────
# SEC-001 fix regressions — add_expense() no longer uses eval()
# ──────────────────────────────────────────────────────────────────────────────

class TestAddExpenseSec001Fix:
    """Regression tests for SEC-001: eval() replaced with float()."""

    def test_add_expense_string_float_is_accepted_sec001(self):
        """Safe numeric strings must still work after removing eval()."""
        expense = add_expense("food", "12.50", "Sandwich")
        assert expense["amount"] == pytest.approx(12.50), (
            "SEC-001 fix must not break normal float-string parsing"
        )

    def test_add_expense_expression_string_raises_value_error_sec001(self):
        """An arithmetic expression (valid for eval, invalid for float) must raise."""
        with pytest.raises(ValueError, match="Invalid amount"):
            add_expense("food", "10+5", "Expression injection attempt")

    def test_add_expense_builtin_import_raises_value_error_sec001(self):
        """__import__() payload must raise ValueError, not execute code."""
        with pytest.raises(ValueError):
            add_expense("food", "__import__('os').getcwd()", "RCE attempt")

    def test_add_expense_exec_payload_raises_value_error_sec001(self):
        """exec() payload must be rejected."""
        with pytest.raises(ValueError):
            add_expense("food", "exec('print(1)')", "exec injection")

    def test_add_expense_zero_amount_is_accepted_sec001(self):
        """Zero is a valid non-negative amount after the fix."""
        expense = add_expense("misc", "0", "Free item")
        assert expense["amount"] == pytest.approx(0.0)

    def test_add_expense_negative_amount_raises_value_error_sec001(self):
        """Negative amounts must be rejected (added as part of SEC-001 fix)."""
        with pytest.raises(ValueError, match="non-negative"):
            add_expense("food", "-1.00", "Negative expense")


# ──────────────────────────────────────────────────────────────────────────────
# BUG-001 fix regressions — get_total() no longer uses EXPENSES[1:]
# ──────────────────────────────────────────────────────────────────────────────

class TestGetTotalBug001Fix:
    """Regression tests for BUG-001: get_total() was skipping first expense."""

    def test_get_total_single_expense_not_zero_bug001(self):
        """With one expense, total must equal that expense, not 0."""
        add_expense("food", "42.00", "Dinner")
        result = get_total()
        assert result == pytest.approx(42.0), (
            f"BUG-001 regression: expected 42.0, got {result}. "
            "First expense must not be skipped."
        )

    def test_get_total_first_expense_included_in_sum_bug001(self):
        """Total must include the FIRST expense added, not start from the second."""
        add_expense("food", "10.00", "First")
        add_expense("food", "20.00", "Second")
        result = get_total()
        assert result == pytest.approx(30.0), (
            f"BUG-001 regression: expected 30.0, got {result}. "
            "EXPENSES[1:] slice must be removed."
        )

    def test_get_total_three_expenses_all_included_bug001(self):
        """All three expenses (including the first) must contribute to the total."""
        add_expense("food", "5.00", "One")
        add_expense("transport", "3.00", "Two")
        add_expense("misc", "2.00", "Three")
        result = get_total()
        assert result == pytest.approx(10.0)

    def test_get_total_category_filter_unaffected_by_bug001(self):
        """Category-filtered totals should include the first matching expense."""
        add_expense("food", "15.00", "First food")   # index 0 in EXPENSES
        add_expense("food", "25.00", "Second food")
        result = get_total("food")
        assert result == pytest.approx(40.0)


# ──────────────────────────────────────────────────────────────────────────────
# BUG-002 fix regressions — get_expenses() now case-insensitive
# ──────────────────────────────────────────────────────────────────────────────

class TestGetExpensesBug002Fix:
    """Regression tests for BUG-002: category filter was case-sensitive."""

    def test_get_expenses_query_title_case_matches_lower_stored_bug002(self):
        """'Food' query must match expense stored as 'food'."""
        add_expense("food", "9.99", "Lunch")
        result = get_expenses("Food")
        assert len(result) == 1, (
            f"BUG-002 regression: expected 1 result for 'Food', got {len(result)}. "
            "Category comparison must be case-insensitive."
        )

    def test_get_expenses_query_all_caps_matches_lower_stored_bug002(self):
        """'FOOD' query must match expense stored as 'food'."""
        add_expense("food", "9.99", "Lunch")
        assert len(get_expenses("FOOD")) == 1

    def test_get_expenses_stored_title_case_found_by_lower_query_bug002(self):
        """Expense stored as 'Food' must be found by query 'food'."""
        add_expense("Food", "9.99", "Lunch")
        result = get_expenses("food")
        assert len(result) == 1

    def test_get_expenses_mixed_stored_casing_all_found_bug002(self):
        """Expenses stored with 'food', 'Food', 'FOOD' all returned for 'food' query."""
        add_expense("food", "1.00", "a")
        add_expense("Food", "2.00", "b")
        add_expense("FOOD", "3.00", "c")
        result = get_expenses("food")
        assert len(result) == 3

    def test_get_expenses_non_matching_category_still_excluded_bug002(self):
        """Different category must still be excluded after case-insensitive fix."""
        add_expense("food", "9.99", "Lunch")
        add_expense("transport", "2.00", "Bus")
        result = get_expenses("food")
        assert len(result) == 1
        assert result[0]["category"] == "food"

    def test_get_total_category_case_insensitive_after_bug002_fix(self):
        """get_total(category) must also work case-insensitively (uses get_expenses)."""
        add_expense("food", "10.00", "Breakfast")
        add_expense("food", "20.00", "Lunch")
        total = get_total("FOOD")
        assert total == pytest.approx(30.0)
