"""Generated unit tests for bug-fix pipeline run 001.

Tests cover: get_expenses (BUG-003 fix, BUG-002 filter fix),
             add_expense (BUG-001 NaN/Infinity fix, BUG-002 blank category fix),
             get_total (BUG-002 empty-string filter fix).

Generated by: Unit Test Generator agent
FIRST-compliant: Fast, Independent, Repeatable, Self-validating, Timely
"""
import math

import pytest
from src.expense_tracker import add_expense, get_expenses, get_total


# Use the autouse fixture from conftest.py (reset_expenses) for independence.
# Do NOT add a second reset fixture here — it is already declared autouse.


class TestGetExpensesBug003Fix:
    """Regression tests for BUG-003: get_expenses() returns defensive dict copies."""

    def test_get_expenses_mutating_returned_dict_preserves_internal_amount_bug003(self):
        """BUG-003: mutating a returned expense dict must not alter the store."""
        add_expense("food", "10.00", "Lunch")
        result = get_expenses()
        result[0]["amount"] = 999.99
        assert get_expenses()[0]["amount"] == pytest.approx(10.0)

    def test_get_expenses_filtered_dict_copy_is_independent_bug003(self):
        """BUG-003: filtered results must also be independent dict copies."""
        add_expense("food", "7.50", "Snack")
        add_expense("transport", "3.00", "Bus")
        food = get_expenses("food")
        food[0]["description"] = "Tampered"
        assert get_expenses("food")[0]["description"] == "Snack"


class TestAddExpenseBug001Fix:
    """Regression tests for BUG-001: reject NaN and Infinity in add_expense()."""

    def test_add_expense_nan_amount_raises_value_error_bug001(self):
        """BUG-001: NaN must be rejected as non-finite."""
        with pytest.raises(ValueError, match="finite non-negative"):
            add_expense("food", "nan", "Not a number")

    def test_add_expense_positive_infinity_raises_value_error_bug001(self):
        """BUG-001: positive infinity must be rejected."""
        with pytest.raises(ValueError, match="finite non-negative"):
            add_expense("food", "inf", "Infinite spend")

    def test_add_expense_negative_infinity_raises_value_error_bug001(self):
        """BUG-001: negative infinity must be rejected."""
        with pytest.raises(ValueError, match="finite non-negative"):
            add_expense("transport", "-inf", "Negative infinity")

    def test_add_expense_finite_amount_is_accepted_bug001(self):
        """BUG-001: finite non-negative amounts must still be accepted."""
        expense = add_expense("food", "19.99", "Dinner")
        assert expense["amount"] == pytest.approx(19.99)
        assert math.isfinite(expense["amount"])


class TestAddExpenseBug002Fix:
    """Regression tests for BUG-002: reject blank categories in add_expense()."""

    def test_add_expense_empty_category_raises_value_error_bug002(self):
        """BUG-002: empty category string must be rejected."""
        with pytest.raises(ValueError, match="non-empty string"):
            add_expense("", "10.00", "No category")

    def test_add_expense_whitespace_category_raises_value_error_bug002(self):
        """BUG-002: whitespace-only category must be rejected."""
        with pytest.raises(ValueError, match="non-empty string"):
            add_expense("   ", "10.00", "Blank category")

    def test_add_expense_valid_category_is_accepted_bug002(self):
        """BUG-002: non-empty category must still be accepted."""
        expense = add_expense("food", "5.00", "Coffee")
        assert expense["category"] == "food"


class TestGetExpensesBug002FilterFix:
    """Regression tests for BUG-002: empty-string filter must not return all expenses."""

    def test_get_expenses_empty_string_filter_returns_empty_list_bug002(self):
        """BUG-002: '' filter must not bypass filtering and return every expense."""
        add_expense("food", "10.00", "Breakfast")
        add_expense("transport", "5.00", "Bus")
        assert get_expenses("") == []

    def test_get_expenses_none_returns_all_expenses_bug002(self):
        """BUG-002: None must still mean 'return all expenses'."""
        add_expense("food", "10.00", "Breakfast")
        add_expense("transport", "5.00", "Bus")
        assert len(get_expenses(None)) == 2


class TestGetTotalBug002Fix:
    """Regression tests for BUG-002: empty-string category filter in get_total()."""

    def test_get_total_empty_string_returns_zero_not_full_sum_bug002(self):
        """BUG-002: get_total('') must not sum all expenses when none match."""
        add_expense("food", "10.00", "Breakfast")
        add_expense("food", "20.00", "Lunch")
        assert get_total("") == pytest.approx(0.0)

    def test_get_total_none_returns_full_sum_bug002(self):
        """BUG-002: get_total(None) must still sum every expense."""
        add_expense("food", "10.00", "Breakfast")
        add_expense("transport", "5.00", "Bus")
        assert get_total(None) == pytest.approx(15.0)
